# Generated by Django 5.2.17 on 2026-08-28 17:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gérante'), ('member', 'Membre')], db_index=True, default='member', max_length=16)),
                ('calendar_color', models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator(message='La couleur doit utiliser le format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('avatar_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['role', 'is_active'], name='accounts_pr_role_69082c_idx')],
            },
        ),
    ]
