# Generated by Django 5.2.17 on 2026-08-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='browser_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='in_app_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
