# Generated by Django 5.2.17 on 2026-08-29 10:06

from django.db import migrations


INITIAL_TYPES = (
    'Réunion client',
    'Shooting',
    'Appel',
    'Réunion interne',
    'Présentation',
    'Déplacement',
    'Congé',
    'Deadline',
    'Autre',
)


def seed_types(apps, schema_editor):
    appointment_type = apps.get_model('calendar_app', 'AppointmentType')
    for name in INITIAL_TYPES:
        appointment_type.objects.get_or_create(name=name)


def remove_seeded_types(apps, schema_editor):
    appointment_type = apps.get_model('calendar_app', 'AppointmentType')
    appointment_type.objects.filter(name__in=INITIAL_TYPES, created_by__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [migrations.RunPython(seed_types, remove_seeded_types)]
