# Generated by Django 5.2.17 on 2026-08-29 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_seed_appointment_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Chaque jour'), ('weekly', 'Chaque semaine'), ('monthly', 'Chaque mois'), ('custom', 'Personnalisée')], max_length=16)),
                ('interval_value', models.PositiveSmallIntegerField(default=1)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurrence_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='calendar_app.recurrenceseries'),
        ),
    ]
